language: cpp

compiler:
  - gcc
#  - clang

before_install:
 - sudo apt-add-repository ppa:sonkun/sfml-stable

 - sudo apt-get update -qq

   # If there is no graphical interface
 - sudo apt-get install -qq mesa-common-dev libglu1-mesa-dev

   # Needed to compile
 - sudo apt-get install -qq libsfml-dev libsfml-dbg

   # Normal dependencies
 - sudo apt-get install -qq libsfml 

script: cmake . && make
